### ISSUE TITLE
start v1 of bot algorithm

### ISSUE THREAD

**Issue by trinile** [Sabine-Sardine/botlbot#24]
V1 : retweet popular tweets (across twitter) 
 based on (( 5 \* # of retweets) + # likes ) / # followers 
filter on keywords (on demand)
generate 5 tweets

**Comment by nthaniel** [comment]
take a look at this link, it may be helpful: https://ursooperduper.github.io/2014/10/28/twitter-bot-with-node-js-part-2.html
